// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aidzpfgurmdgisbkhgzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZHpwZmd1cm1kZ2lzYmtoZ3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDUwMTksImV4cCI6MjA1OTMyMTAxOX0.5eRjNpd0_8KfmbhkGcrFwmBvq7m0eyUZ5cPEukPCyLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);